config/routes.rb
Blog::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :entries, :only => [:index, :show] do
		collection do
			get :category
			get :tag
			get :archive
		end
  end

  root :to => 'entries#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :entries
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :category
	has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < InheritedResources::Base

  def category
    return redirect_to collection_url unless params[:id]

    @category = Category.find(params[:id])
    @entries = @category.entries
  end

  def tag
    return redirect_to collection_url unless params[:id]

    @tag = Tag.find(params[:id])
    @entries = @tag.entries
  end

  def archive
    # return redirect_to collection_url unless params[:id]

    @entries = Entry.find(:all, :order => 'created_at, id')
    @entry_months = @entries.group_by { |e| e.created_at.beginning_of_month }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
		markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,:autolink => true, :space_after_headers => true)
		markdown.render(text).html_safe
	end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/application/_meta.html.erb
<title>Curious -キュリアス | ギークになりたい系女子のてきとーブログ-</title>

<meta charset="utf-8">

<meta http-equiv="content-language" content="ja" />
<meta http-equiv="content-style-type" content="text/css" /> 
<meta http-equiv="content-script-type" content="text/javascript" />

<meta name="description" content="" />
<meta name="keywords" content="" />

<meta name="copyright" content="ErinaMikami" />
<meta name="viewport" content="width=1100" />

<meta name="robots" content="index,follow" />
<meta http-equiv="imagetoolbar" content="no" />

<!--[if lt IE 9]>
<script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/application/_side_content.html.slim
.side_content
	header
		h1 = link_to image_tag("layouts/logo.png", {:alt => ""}), root_path

	nav
		= render "application/nav_module/nav_profile"
		= render "application/nav_module/nav_category"
		= render "application/nav_module/nav_archive"
		= render "application/nav_module/nav_tag"

app/views/application/nav_module/_nav_archive.html.slim
section.nav_module
	h1 =image_tag "layouts/nav_module/h_archive.png", :alt => "アーカイブ"

	- @entries = Entry.find(:all, :order => 'created_at, id')
	- @entry_months = @entries.group_by { |e| e.created_at.beginning_of_month }

	ul.tree_list
		- @entry_months.sort.each do |month, entries|
			li = link_to "#{month.strftime('%Y年%m月')} (10)", "#"
		
	aside.more_link = link_to "もうちょい読む", archive_entries_path

app/views/application/nav_module/_nav_category.html.slim
section.nav_module
	h1 =image_tag "layouts/nav_module/h_category.png", :alt => "カテゴリー"

	ul.tree_list
		- Category.all.each do |category|
			- if category.entries.presence
				li = link_to "#{category.name} (#{category.entries.count})", category_entries_path(:id => category.id)

app/views/application/nav_module/_nav_profile.html.slim
section.nav_module.nav_profile
	h1 =image_tag "layouts/nav_module/h_profile.png", :alt => "プロフィール"

	figure = image_tag "layouts/nav_module/img_profile.png", :alt => "プロフィール画像"
	p.name 三上絵利菜
	p.catch @skyguild<br />三度の飯より酒が好き
	p.description 
		|FICC inc.所属 Webディベロッパ
		br
		|日本電子専門学校Webデザイン科卒
		br
		|SetucoCMSプロジェクトリーダー

	aside.more_link = link_to "もうちょい読む", "#"

app/views/application/nav_module/_nav_tag.html.slim
section.nav_module.nav_tag
	h1 =image_tag "layouts/nav_module/h_tag.png", :alt => "タグクラウド"

	ul.tag_cloud
		- Tag.all.each do |tag|
			li.lv3 = link_to tag.name, tag_entries_path(:id => tag.id)

	/ aside.more_link = link_to "もっとあるよ", "#"

app/views/entries/_entry_list.html.slim
- if @entries.presence
	- @entries.each do |entry|
		article
			header
				p.date : time = entry.created_at.strftime("%Y/%m/%d")
				h1 = link_to entry.title, entry
				aside.social_btns
					ul
						li.hatena
						li.tweet
						li.google_plusone
						li.facebook_like

			.body
				.markdown = markdown(entry.body)

				aside.link_bar
					= link_to entry do
						span 続きを読む

			footer
				.label_list
					dl.category
						dt = image_tag "entries/icn_category.png", :alt => "カテゴリー"
						dd = link_to entry.category.name, category_entries_path(:id => entry.category.id)

					dl.tag
						dt = image_tag "entries/icn_tag.png", :alt => "タグ"
						- if entry.tags.presence
							- entry.tags.each do |tag|
								dd = link_to tag.name, tag_entries_path(:id => tag.id)
						- else
							dd なし

					dl.comment
						dt = image_tag "entries/icn_comment.png", :alt => "コメント"
						dd = link_to "0コメント", "#"
- else
	p.blank まだエントリーがありません。

app/views/entries/archive.html.slim
header
	h1 月別アーカイブ

- @entry_months.sort.each do |month, entries|
	h2 #{month.strftime('%Y年%m月')} のエントリー
	ul
	- entries.each do |entry|
		li = link_to entry.title, entry

app/views/entries/category.html.slim
header
	h1 #{@category.name} のエントリー一覧

= render "entry_list"

app/views/entries/index.html.slim
= render "entry_list"

app/views/entries/show.html.slim
article
	header
		p.date : time = @entry.created_at.strftime("%Y/%m/%d")
		h1 :span = @entry.title
		aside.social_btns
			ul
				li.hatena
				li.tweet
				li.google_plusone
				li.facebook_like

	.body
		.markdown = markdown(@entry.body)

		aside.social_btns
			ul
				li.hatena
				li.tweet
				li.google_plusone
				li.facebook_like

	footer
		.label_list
			dl.category
				dt = image_tag "entries/icn_category.png", :alt => "カテゴリー"
				dd = link_to @entry.category.name, category_entries_path(:id => @entry.category.id)

			dl.tag
				dt = image_tag "entries/icn_tag.png", :alt => "タグ"
				- if @entry.tags.presence
					- @entry.tags.each do |tag|
						dd = link_to tag.name, tag_entries_path(:id => tag.id)
				- else
					dd なし

			dl.comment
				dt = image_tag "entries/icn_comment.png", :alt => "コメント"
				dd = link_to "0コメント", "#"

		aside.link_bar
			= link_to collection_url do
				span 一覧へ戻る

app/views/entries/tag.html.slim
header
	h1 #{@tag.name} のエントリー一覧

= render "entry_list"

app/views/layouts/application.html.slim
doctype html
html
  head
    = render "meta"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body id="#{params[:controller]}" class="#{params[:action]}"
  	.content : .inner
  		.main_content
		    = yield

		    footer
		    	p Copyright (c) 2012 ErinaMikami All Rights Reserved.
		  
		  = render "side_content"